### PR TITLE
chore: added cypress/screenshots to git ignore

### PR DESCRIPTION
**Pull request by nickytonline**
### Summary

Cypress snapshots were showing up in my git changes, so adding the folder to the .gitignore.

### Test plan

1. This doesn't changed code, so all existing previews should deploy and tests pass.

### Standard checks:

- [ ] Check the Deploy Preview's Demo site for your PR's functionality
- [ ] Add docs when necessary

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

Someone sweeping up a cat jokingly

### CODE REVIEW

**Review by sarahetter — APPROVED** [review]
LGTM, but as sand: is there any way to turn off these screenshots?

**Comment by nickytonline** [comment]
> LGTM, but as sand: is there any way to turn off these screenshots?

You can. It's a setting in the Cypress configuration file. It's on to capture errors as screenshots. You can have a different configuration for local development if you want to get rid of them for local dev. We can do that, but it'd mean creating separate config files for each demo site locally and when you call them, load a config for the development environment.

Here's an example of how to run it based on the environment variable. https://github.com/forem/forem/blob/main/cypress/plugins/index.js

**Comment by ascorbic** [comment]
I think the screenshots are helpful in general. The problem is ones like this, where they're failing for some weird reason. I've seen this before, but don't know why it happens. Why is it showing app.netlify.com, instead of the demo site?

**Comment by sarahetter** [comment]
> Why is it showing app.netlify.com, instead of the demo site?
This is because of the cancelled build previews (due to the netlify.toml `ignore`, as we were just talking about on slack)
If the build fails, then the action gets passed app.netlify.com instead of the actual build preview url.

**Pull request merged**
