### PR TITLE
chore: update RSC demo with new router syntax

### PR DESCRIPTION
**Pull request by ascorbic**
### Summary

Next 12.1.6 no longer injects the router into RSC pages. This PR updates the RSC demo site to match the new syntax, and updates the version of next to the latest canary. 

### Test plan

1. Visit the server-components deploy preview
2. Open the RSC demo and click through to the comments page of an item
3. Page renders without error

### Relevant links (GitHub issues, Notion docs, etc.) or a picture of cute animal

two capybaras

### Standard checks:

- [ ] Check the Deploy Preview's Demo site for your PR's functionality
- [ ] Add docs when necessary

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

**Review by nickytonline — DISMISSED** [review]
Compared it to the next RSC demo repo and looks good! 🚀

**Review by ericapisani — APPROVED** [review]
Do we want to continue to have the RSC demo be an edge demo as well? 

Noticed the configuration for it is removed as part of these changes and just wanted to confirm that we have another demo with edge functionality enabled that could be used

Other than that one question, LGTM

**Comment by ascorbic** [comment]
@ericapisani It's not needed because the default runtime for the site is set to edge: https://github.com/netlify/netlify-plugin-nextjs/pull/1339/files#diff-762920f460ca76432144cf8b30856f6e705b2a888ced40a2f12e21e3a15794f5L3

**Comment by ericapisani** [comment]
@ascorbic Ah, I missed that, thanks for the link!

**Pull request merged**
