### PR TITLE
fix: add details to copyNextAssets error messaging

### PR DESCRIPTION
**Pull request by tmilewski**
I wound up spending an inordinate amount of time trying to debug issues when attempting to deploy with NX while using this plugin.

Having these specific details would have saved me a lot of trouble. Hopefully, this change will help others down the line.

Thanks for all of your work!

### CODE REVIEW

**Review by lindsaylevine — APPROVED** [review]
thanks for this @tmilewski!

**Comment by lindsaylevine** [comment]
@tmilewski hey tom! i was gonna do this for you but since you PR'd from a fork.. can you do me a favor and rebase this with main so we can get the tests passing? thanks so much :)

**Comment by lindsaylevine** [comment]
turns out matt could do it! we'll merge when everything passes 🙏 thanks matt!!!

**Comment by tmilewski** [comment]
@lindsaylevine Apologies for falling off... I've been neck-deep trying to get a project out. Thanks to you and @ascorbic for getting this through!

**Comment by lindsaylevine** [comment]
no worries, of course!!!

**Pull request merged**
