### PR TITLE
feat: Include basePath property in NEXTAUTH_URL when present in config

### PR DESCRIPTION
**Pull request by ericapisani**
### Summary

This was missed in the initial implementation of adding out of the box NextAuth support (see #1242 ), but is something that is needed when the `basePath` property exists within the `next.config.js` file. Related docs on NextAuth can be found [here](https://next-auth.js.org/configuration/options#nextauth_url)

### Test plan

1. Visit the Deploy Preview [here](https://deploy-preview-1336--netlify-plugin-nextjs-next-auth-demo.netlify.app/)

### Relevant links (GitHub issues, Notion docs, etc.) or a picture of cute animal
trash_panda

### Standard checks:

- [ ] Check the Deploy Preview's Demo site for your PR's functionality

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

**Comment by nickytonline** [comment]
CleanShot 2022-05-02 at 11 54 41


@ericapisani, the demo site exited early during build.

```
11:05:54 AM: Build ready to start
11:06:00 AM: build-image version: d2c6dbeac570350a387d832f64bc980dc964ad65 (focal)
11:06:00 AM: build-image tag: v4.8.0
11:06:00 AM: buildbot version: a018caed2ab46726023e1532e0d3214727318b1c
11:06:00 AM: Fetching cached dependencies
11:06:01 AM: Starting to download cache of 239.1MB
11:06:03 AM: Finished downloading cache in 2.728393725s
11:06:03 AM: Starting to extract cache
11:06:07 AM: Finished extracting cache in 4.257576514s
11:06:07 AM: Finished fetching cache in 7.005896418s
11:06:07 AM: Starting to prepare the repo for build
11:06:08 AM: Preparing Git Reference pull/1336/head
11:06:08 AM: Parsing package.json dependencies
11:06:09 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'demos/next-auth/.next' versus '.next' in the Netlify UI
11:06:09 AM: Different build command detected, going to use the one specified in the Netlify configuration file: 'next build' versus 'npm run build' in the Netlify UI
11:06:09 AM: Detected ignore command in Netlify configuration file. Proceeding with the specified command: 'git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../plugin'
11:06:09 AM: User-specified ignore command returned exit code 0. Returning early from build.
11:06:09 AM: Creating deploy upload records
11:06:09 AM: Failed during stage 'checking build content for changes': Canceled build due to no content change
11:06:09 AM: Finished processing build request in 8.965846734s
```

**Comment by ericapisani** [comment]
@nickytonline Not quite sure what happened but I'm seeing a successful build message 🤔 

Screen Shot 2022-05-02 at 12 18 42 PM

This is also the most recent build log on the Netlify UI side so maybe it was just an initial hiccup and merging the main branch into this branch was what it needed to sort itself out

Screen Shot 2022-05-02 at 12 21 26 PM

**Comment by sarahetter** [comment]
I'm seeing the same thing as Erica, fwiw

**Review by nickytonline — APPROVED** [review]
Tested the demo site locally and it looks good. Same for tests. 🚀

**Pull request merged**
